# automation:
  - alias: 'Start HomeKit'
    trigger:
      - platform: homeassistant
        event: start
    action:
      - delay: '00:05'  # Waits 5 minutes
      - service: homekit.start
      
  - alias: 'Dryer Ends'
    trigger:
      - platform: numeric_state
        entity_id: sensor.dryer_amps
        below: .3
        for:
          seconds: 10
    condition:
      - condition: state
        entity_id: switch.dryer
        state: 'on'
      - condition: state
        entity_id: device_tracker.rudders_iphone_xs_max
        state: "home"
      
    action:
      service_template: notify.pushover
      data_template: 
        title: "Dryer Finished"
        message: "Looks like the dryer has finished"

  - alias: 'Dryer Airing'
    trigger:
      - platform: numeric_state
        entity_id: sensor.dryer_amps
        below: 2.0
        above: .3
        for:
          seconds: 20
    condition:
      - condition: state
        entity_id: switch.dryer
        state: 'on'
      - condition: state
        entity_id: device_tracker.rudders_iphone_xs_max
        state: "home"
    action:
      service_template: notify.pushover
      data_template: 
        title: "Dryer Airing"
        message: "Looks like the dryer is Airing"
        
        
  - alias: 'Washing Ends'
    trigger:
      - platform: numeric_state
        entity_id: sensor.washing_machine_amps
        below: .2
        for:
          seconds: 120
    condition:
      - condition: state
        entity_id: switch.washing_machine
        state: 'on'
      - condition: state
        entity_id: device_tracker.rudders_iphone_xs_max
        state: "home"
#         - condition: time
#           after: '06:00:00'
#           before: '20:00:00'
    action:
      service_template: notify.pushover
      data_template: 
        title: "Washing Finished"
        message: "Looks like the washing has finished"

#         
#         
#         - service: tts.google_say
#           entity_id:
#             - media_player.kitchen_home
#             - media_player.gaming_room_home
#             - media_player.ensuite_speaker
#           data_template:
#             message: "The washing machine has finished"
#         - service: input_boolean.turn_off
#           entity_id: input_boolean.washing_active