resources:
  - url: /local/tracker-card.js?v=0.1.5
    type: js
  - url: /local/slider-entity-row.js
    type: js
  - url: /local/mini-media-player.js?v=0.9.8
    type: module
name: The Onion
views:
  - id: 0
    title: Home
    icon: 'mdi:lightbulb-on'
    name: Home
    cards:
      - id: 293ec8e56cfd47b5b002e842da389d94
        type: vertical-stack
        cards:
          - type: glance
            show_state: false
            title: Living Room
            entities:
              - entity: scene.good_morning
                name: Bright
                tap_action: call-service
                icon: 'mdi:ceiling-light'
                service: scene.turn_on
              - entity: scene.watch_tv
                name: Dim
                tap_action: call-service
                icon: 'mdi:lightbulb-outline'
                service: scene.turn_on
              - entity: scene.goodnight
                name: 'Off'
                tap_action: call-service
                icon: 'mdi:bed-empty'
                service: scene.turn_on
              - entity: media_player.sony_bravia_tv
                name: TV Off
                tap_action: call-service
                icon: 'mdi:television'
                service: media_player.turn_off
              - entity: input_boolean.show_lounge_controls
                name: more
                tap_action: toggle
          - type: conditional
            conditions:
              - entity: input_boolean.show_lounge_controls
                state: 'on'
            card:
              type: entities
              entities:
                - entity: light.table_lamp
                  name: Side Table
                  icon: 'mdi:lamp'
                  type: 'custom:slider-entity-row'
                - entity: light.hugo
                  name: Sideboard
                  type: 'custom:slider-entity-row'
                - entity: light.pendant
                  name: Pendant
                  icon: 'mdi:ceiling-light'
                  type: 'custom:slider-entity-row'
                - entity: media_player.sony_bravia_tv
                  type: 'custom:mini-media-player'
                  icon: 'mdi:television'
                  group: true
                  hide_volume: true
                  power_color: true
                  hide_controls: true
                - entity: media_player.lounge
                  type: 'custom:mini-media-player'
                  hide_controls: true
                  name: Sonos SoundBar
                  hide_power: true
                  group: true
                - type: divider
                - entity: light.hue_color_lamp_1_2
                  name: Pendant
                  icon: 'mdi:ceiling-light'
                  type: 'custom:slider-entity-row'
                - entity: light.dimmable_light_1
                  name: Bookcase
                  icon: 'mdi:book'
                  type: 'custom:slider-entity-row'
                - type: divider
                - entity: binary_sensor.washing_machine
                  name: Washing Machine Running
                  secondary_info: last-changed
                - entity: binary_sensor.dryer
                  name: Dryer Running
                  secondary_info: last-changed
      - id: 029f6c7ce1a548baa5562a8d0a5f7a4c
        type: glance
        columns: 6
        entities:
          - entity: light.porch
            name: Porch
            tap_action: toggle
          - entity: light.dining_pendant
            tap_action: toggle
            name: Dining
            icon: 'mdi:ceiling-light'
          - entity: light.macrame
            tap_action: toggle
          - entity: light.hue_white_lamp_1
            name: BBQ
            tap_action: toggle
          - entity: switch.festoon_lights
            name: Festoon
            tap_action: toggle
            icon: 'mdi:lightbulb-on-outline'
          - entity: group.shed_lights
            name: Shed
            icon: 'mdi:home-outline'
            tap_action: toggle
          - entity: light.hue_color_lamp_1_2
            name: Pendant
            icon: 'mdi:ceiling-light'
            tap_action: toggle
          - entity: light.dimmable_light_1
            name: Bookcase
            icon: 'mdi:book'
            tap_action: toggle
      - id: e7406c65700e42419bd36de373d93009
        type: picture-entity
        title: Back Door
        name: Back Door
        entity: camera.backdoor
      - id: 31667e7441e14460b5a45af41ac14e1b
        type: glance
        columns: 4
        show_name: false
        entities:
          - entity: sensor.pws_station_id
            name: Newtown
          - entity: sensor.pws_temp_c
            name: Temp
          - entity: sensor.pws_relative_humidity
            name: Humid
          - entity: sensor.pws_precip_today_metric
            name: Rain
          - sensor.pws_weather
          - sensor.pws_temp_low_1d_c
          - sensor.pws_temp_high_1d_c
          - sensor.pws_precip_1d
          - sensor.pws_weather_2d_metric
          - sensor.pws_temp_low_2d_c
          - sensor.pws_temp_high_2d_c
          - sensor.pws_precip_2d
      - id: e123123412
        type: glance
        title: Mitchell's Room
        show_name: false
        columns: 2
        entities:
          - entity: sensor.mitchells_room_temperature
            name: Temp
          - entity: sensor.mitchells_room_humidity
            name: Humidity
      - id: 27a47f55396345aea93f0eee86fd255f
        type: glance
        entities:
          - sensor.ocl_stock
          - sensor.budget__erskineville_p98
      - id: ad39bf8170f94094b578e4dd5db08945
        type: conditional
        conditions:
          - entity: sensor.pws_precip_1d
            state_not: 'x'
        card:
          type: picture-entity
          entity: camera.sydney_radar
#           image: 'http://www.bom.gov.au/radar/IDR714.gif'
      - id: 032ab74b51934e259cad896bfd631558
        type: history-graph
        hours_to_show: 240
        entities:
          - sensor.budget__erskineville_p98
      - id: bd254293f396423f8630560e074e7005
        type: iframe
        url: >-
          https://grafana.binarylight.com.au/d-solo/xv9C3pWmk/ha-dasboard?panelId=26&orgId=1&tab=metrics"
          width="450" height="200" frameborder="0"
  - id: 1
    title: Media
    icon: 'mdi:television-classic'
    name: Media Control
    cards:
      - id: 95f335d768714846bd18830f82772c9e
        type: entities
        title: TV
        entities:
          - entity: media_player.sony_bravia_tv
            type: 'custom:mini-media-player'
            group: true
            hide_volume: true
            power_color: true
            hide_controls: true
          - entity: media_player.lounge
            type: 'custom:mini-media-player'
            hide_controls: true
            name: Sonos SoundBar
            hide_power: true
            group: true
      - id: 25325e053fb448e0b24f91a3804fd75d
        type: glance
        title: Sonos
        entities:
          - media_player.bathroom
          - media_player.bbq
          - media_player.garden
          - media_player.kitchen
          - media_player.lexies_sonos_one
          - media_player.music_room
      - id: 228ad12cd018469fb76ae4a7178d66bc
        type: entities
        title: Living Room
        entities:
          - entity: media_player.sony_bravia_tv
            name: TV
          - entity: media_player.lounge
            name: TV Sound
          - entity: media_player.living_room
            name: AppleTV
      - id: ee6327b60c7c4dd9962e03cc12d821b5
        type: entities
        title: Shed
        entities:
          - entity: media_player.viera_st60_series
            name: Panasonic TV
          - entity: media_player.shed_tv
            name: Shed AppleTV
  - id: 2
    title: Weather
    icon: 'mdi:weather-partlycloudy'
    name: Weather
    cards:
      - id: ad0ca38fb90d4cf59df4ac80eeea72a5
        type: entities
        title: BOM Forecast
        entities:
          - sensor.bom_forecast_sydney_0
          - sensor.bom_forecast_sydney_1
          - sensor.bom_forecast_sydney_2
          - sensor.bom_forecast_sydney_3
      - id: 07f46f7df3ab43d8b8b66fa41e3f7252
        type: glance
        title: Sydney BOM
        entities:
          - entity: sensor.bom_sydney_0_max
            name: Max
            icon: 'mdi:thermometer'
      - id: 840bb961d7c84e81ae4b28af0dced14c
        type: vertical-stack
        cards:
          - type: glance
            title: Newtown Now
            entities:
              - entity: sensor.pws_temp_c
                name: Temp
              - entity: sensor.pws_relative_humidity
                name: Humid
              - entity: sensor.pws_precip_today_metric
                name: Rain
              - entity: sensor.pws_wind_kph
                name: Wind
              - entity: sensor.pws_wind_1d_kph
                name: Ave Wind
              - entity: sensor.pws_wind_gust_1d_kph
                name: Gust
              - entity: sensor.pws_wind_dir
                name: Dir
              - entity: sensor.pws_uv
                name: UV
              - entity: sensor.mitchells_room_temperature
                name: Mitch
              - entity: sensor.aeotec_zw100_multisensor_6_temperature_2
                name: Kitchen
              - entity: sensor.aeotec_zw100_multisensor_6_temperature
                name: Shed
          - type: glance
            title: Newtown Today/Tom
            columns: 4
            show_name: false
            entities:
              - sensor.pws_weather
              - sensor.pws_temp_high_1d_c
              - sensor.pws_temp_low_1d_c
              - sensor.pws_precip_1d
              - sensor.pws_weather_2d_metric
              - sensor.pws_temp_high_2d_c
              - sensor.pws_temp_low_2d_c
              - sensor.pws_precip_2d
      - id: ce5692f48a42429eaaec6ccf7158c3ef
        type: history-graph
        hours_to_show: 48
        entities:
          - entity: sensor.bom_sydney_conditions_air_temp_c
            name: Sydney
          - entity: sensor.bom_sydney_conditions_feels_like_c
            name: Feels Like
          - entity: sensor.pws_temp_c
            name: Newtown
          - entity: sensor.aeotec_zw100_multisensor_6_temperature_2
            name: Kitchen
          - entity: sensor.aeotec_zw100_multisensor_6_temperature
            name: Shed
          - entity: sensor.mitchells_room_temperature
            name: Mitch
      - id: 10fa5c0ffd114ddfa6af804636aa5cc5
        type: entities
        title: BOM Now
        entities:
          - sensor.bom_sydney_conditions_weather
          - sensor.bom_sydney_conditions_air_temp_c
          - sensor.bom_sydney_conditions_feels_like_c
          - sensor.bom_sydney_conditions_rain_today
          - sensor.bom_sydney_conditions_relative_humidity
          - sensor.bom_sydney_conditions_dew_point_c
          - sensor.bom_sydney_conditions_wind_direction
          - sensor.bom_sydney_conditions_wind_gust_kmh
          - sensor.bom_sydney_conditions_wind_speed_kmh
          - sensor.bom_sydney_conditions_pressure_mb
          - sensor.bom_sydney_conditions_visability_km
      - id: 85329d54a4a543cebdbc8ef7d97ba75d
        type: entities
        title: Forecast
        entities:
          - sensor.pws_weather_1d_metric
          - sensor.pws_weather_1n_metric
          - sensor.pws_weather_2d_metric
          - sensor.pws_weather_2n_metric
          - sensor.pws_weather_3d_metric
          - sensor.pws_weather_3n_metric
          - sensor.pws_weather_4d_metric
          - sensor.pws_weather_4n_metric
      - id: 6d043e091a894914b6071ae5bf964d04
        type: picture
        image: 'http://www.bom.gov.au/radar/IDR714.gif'
      - id: 8274ffef8a2649e690a245c643c428fe
        type: iframe
        url: 'https://embed.windy.com/embed2.html'
        title: Weather radar
  - id: 3
    title: Ovals
    icon: 'mdi:gate'
    name: Ovals
    cards:
      - id: 3bcadeac4fe844e68c18d67609f8a2ee
        type: entities
        entities:
          - sensor.ado
          - sensor.trumper
          - sensor.drummoyne
          - sensor.heffron
          - sensor.jubilee
          - sensor.bat_and_ball
          - sensor.david_philips_south
          - sensor.mackey_park
          - sensor.steel_park
  - id: 4
    title: HA Host
    icon: 'mdi:home-assistant'
    name: HA Host
    cards:
      - id: 40b3c4759dbd425da429974ada7697f8
        type: glance
        columns: 3
        entities:
          - sensor.last_boot
          - entity: sensor.homeassistant_v2db
            name: DB
          - entity: sensor.homeassistantlog
            name: log
      - id: c0b153721e254ff0a6212c8539faa826
        type: history-graph
        entities:
          - sensor.mariadb_size
          - sensor.state_changesminute
      - id: 995df9d65e2741d49c7e364740626ac1
        type: entities
        entities:
          - sensor.glances_containers_active
          - sensor.glances_containers_cpu_used
          - sensor.glances_cpu_load
          - sensor.glances_cpu_temp
          - sensor.glances_disk_free
          - sensor.glances_disk_used
          - sensor.glances_disk_used_2
          - sensor.glances_ram_free
          - sensor.glances_ram_used
          - sensor.glances_ram_used_2
          - sensor.glances_running
          - sensor.glances_sleeping
          - sensor.glances_swap_free
          - sensor.glances_swap_used
          - sensor.glances_swap_used_2
      - id: 16db27cd1aa4410398d0b21e8daaf6c9
        type: history-graph
        entities:
          - sensor.glances_cpu_load
          - sensor.glances_ram_free
          - sensor.glances_disk_free
      - id: 22853fdddc0f4651b48b0090accc85b8
        type: 'custom:tracker-card'
        title: Custom Tracker
        trackers:
          - sensor.custom_component_tracker
          - sensor.custom_card_tracker
  - id: 5
    title: NAS
    icon: 'mdi:server'
    name: NAS
    cards:
      - id: 976b8e5bb6ce41d9955059003d9df17c
        type: history-graph
        entities:
          - entity: sensor.onionnas_network_down_eth0
            name: eth0 Down
          - entity: sensor.onionnas_network_up_eth0
            name: eth0 Up
          - entity: sensor.onionnas_cpu_usage
            name: CPU %
          - entity: sensor.onionnas_memory_usage
            name: MEM %
          - entity: sensor.onionnas_system_temperature
            name: CPU
          - entity: sensor.onionnas_temperature_drive_01
            name: Drive 1
          - entity: sensor.onionnas_temperature_drive_02
            name: Drive 2
          - entity: sensor.onionnas_temperature_drive_03
            name: Drive 3
          - entity: sensor.onionnas_temperature_drive_04
            name: Drive 4
      - id: 8269a318d43e44b6b9fa41dc6060062e
        type: vertical-stack
        cards:
          - type: entities
            name: Statistics
            entities:
              - sensor.onionnas_cpu_temperature
              - sensor.onionnas_cpu_usage
              - sensor.onionnas_memory_available
              - sensor.onionnas_memory_usage
              - sensor.onionnas_memory_used
              - sensor.onionnas_network_link_eth0
              - sensor.onionnas_network_up_eth0
              - sensor.onionnas_network_down_eth0
          - type: glance
            name: Drives
            columns: 4
            entities:
              - entity: sensor.onionnas_smart_status_drive_01
                name: Drive 1
              - entity: sensor.onionnas_smart_status_drive_02
                name: Drive 2
              - entity: sensor.onionnas_smart_status_drive_03
                name: Drive 3
              - entity: sensor.onionnas_smart_status_drive_04
                name: Drive 4
  - id: 6
    title: Network
    icon: 'mdi:lan'
    name: Network
    cards:
      - id: a3e35336a610467d82b6d44a7d46f9af
        type: vertical-stack
        cards:
          - type: glance
            name: Speedtest
            title: Speedtest
            entities:
              - sensor.speedtest_download
              - sensor.speedtest_upload
              - sensor.speedtest_ping
          - type: history-graph
            hours_to_show: 72
            entities:
              - sensor.speedtest_download
              - sensor.speedtest_upload
      - id: 99551fd3efd74268ba4e6a2e15eb7b8d
        type: vertical-stack
        cards:
          - type: glance
            name: Transmissiom
            title: Transmission
            entities:
              - entity: sensor.transmission_down_speed
                name: Down
              - entity: sensor.transmission_up_speed
                name: Up
              - entity: sensor.transmission_total_torrents
                name: Total
              - entity: sensor.transmission_active_torrents
                name: Active
              - entity: switch.transmission_turtle_mode
                tap_action: toggle
                name: Switch
          - type: history-graph
            hours_to_show: 72
            entities:
              - entity: sensor.transmission_down_speed
                name: Down
              - entity: sensor.transmission_up_speed
                name: Up
          - type: history-graph
            entities:
              - sensor.washing_machine_amps
              - sensor.dryer_amps
