resources:
  - url: /local/tracker-card.js?v=0.1.4
    type: js

name: The Onion
views:
  - title: Lights
    icon: mdi:lightbulb-on
    name: Lights
    cards:
      - type: glance
        column_width: 25%
        entities:
         - entity: light.table_lamp
           name: Side Table
           tap_action: toggle
         - entity: light.hugo
           name: Bookcase
           tap_action: toggle
         - entity: light.pendant
           name: Pendant
           tap_action: toggle
         - entity: light.dining_pendant
           tap_action: toggle
           name: Dining
      - type: glance
        column_width: 25%
        entities:
         - entity: light.porch
           name: Porch
           tap_action: toggle
         - entity: light.macrame
           tap_action: toggle
         - entity: switch.festoon_lights
           name: Festoon
           tap_action: toggle
         - entity: group.shed_lights
           name: Shed
           tap_action: toggle
#          - entity: light.shed_2
#            tap_action: toggle

#       - type: entities
#         title: Lights
#         entities:
#          - light.porch
#          - light.table_lamp
#          - light.hugo
#          - light.pendant
#          - light.dining_pendant
#          - light.macrame
#          - switch.festoon_lights
#          - light.shed_1
#          - light.shed_2
         
      - type: entities
        title: Heater
        show_header_toggle: false
        entities:
          - entity: binary_sensor.gas_heater
            name: Heater On/Off
            secondary_info: last-changed
          - entity: sensor.heater_current
            name: Heater Current
            secondary_info: last-changed
          - entity: switch.heater_switch
            name: Heater Wall Switch
          
      - type: glance
        entities:
          - sensor.ocl_stock
          - sensor.budget__erskineville_p98
      - type: history-graph
        hours_to_show: 240
        entities:
          - sensor.budget__erskineville_p98
          
#       - type: iframe
#         title: Erko 98 RON
#         url: https://grafana.binarylight.com.au/render/d-solo/xv9C3pWmk/ha-dasboard?panelId=22&orgId=1&from=1532928972819&to=1533533772820&tab=general&width=1000&height=500&tz=UTC%2B10%3A00
        
      - type: picture-entity
        title: Back Door
        name: Back Door
        entity: camera.backdoor

  - title: Media
    icon: mdi:television-classic
    name: Media Control
    cards:
      - type: glance
        title: Sonos
        entities:
         - media_player.bathroom
         - media_player.bbq
         - media_player.garden
         - media_player.kitchen
         - media_player.lexies_sonos_one
         - media_player.music_room
      - type: entities
        title: Living Room
        entities:
         - entity: media_player.sony_bravia_tv
           name: TV
         - entity: media_player.lounge
           name: TV Sound
         - entity: media_player.living_room
           name: AppleTV

      - type: entities
        title: Shed
        entities:
         - entity: media_player.viera_st60_series
           name: Panasonic TV
         - entity: media_player.shed_tv
           name: Shed AppleTV

  - title: Weather
    icon: mdi:weather-partlycloudy
    name: Weather
    cards:  
      - type: vertical-stack
        cards:
          - type: glance
            title: Newtown Now
            entities:
            #  - sensor.pws_station_id
             - entity: sensor.pws_temp_c
               name: Temp
             - entity: sensor.pws_relative_humidity
               name: Humid
             - entity: sensor.pws_precip_today_metric
               name: Rain
             - entity: sensor.pws_wind_kph
               name: Wind
             - entity: sensor.pws_wind_1d_kph
               name: Ave Wind
             - entity: sensor.pws_wind_gust_1d_kph
               name: Gust
             - entity: sensor.pws_wind_dir
               name: Dir
             - entity: sensor.pws_uv
               name: UV
             - entity: sensor.kitchen_temperature
               name: Kitchen
             - entity: sensor.shed_temperature
               name: Shed
          - type: glance
            title: Newtown Today/Tom
            column_width: 25%
            show_name: false
            entities:
#              - entity: sensor.pws_station_id
#                icon: mdi:calendar
#                name: Today
             - sensor.pws_weather
             - sensor.pws_temp_high_1d_c
             - sensor.pws_temp_low_1d_c
             - sensor.pws_precip_1d    
#           - type: glance
#             show_name: false
#             column_width: 25%
#             title: Newtown Tomorrow
#             entities:
#              - entity: sensor.pws_station_id
#                icon: mdi:calendar-plus
#                name: Tomorrow
             - sensor.pws_weather_2d_metric
             - sensor.pws_temp_high_2d_c
             - sensor.pws_temp_low_2d_c
             - sensor.pws_precip_2d

      - type: history-graph
        entities:
          - entity: sensor.bom_sydney_conditions_air_temp_c
            name: Sydney
          - entity: sensor.bom_sydney_conditions_feels_like_c
            name: Feels Like
          - entity: sensor.pws_temp_c
            name: Newtown
          - entity: sensor.kitchen_temperature
            name: Kitchen
          - entity: sensor.shed_temperature
            name: Shed
        
      - type: entities
        title: BOM Now
        entities:
          - sensor.bom_sydney_conditions_weather
          - sensor.bom_sydney_conditions_air_temp_c
          - sensor.bom_sydney_conditions_feels_like_c
          - sensor.bom_sydney_conditions_rain_today
          - sensor.bom_sydney_conditions_relative_humidity
          - sensor.bom_sydney_conditions_dew_point_c
          - sensor.bom_sydney_conditions_wind_direction
          - sensor.bom_sydney_conditions_wind_gust_kmh
          - sensor.bom_sydney_conditions_wind_speed_kmh
          - sensor.bom_sydney_conditions_pressure_mb
          - sensor.bom_sydney_conditions_visability_km
          
      - type: entities
        title: Forecast
        entities:
          - sensor.pws_weather_1d_metric
          - sensor.pws_weather_1n_metric
          - sensor.pws_weather_2d_metric
          - sensor.pws_weather_2n_metric
          - sensor.pws_weather_3d_metric
          - sensor.pws_weather_3n_metric
          - sensor.pws_weather_4d_metric
          - sensor.pws_weather_4n_metric

      - type: picture
        image: http://www.bom.gov.au/radar/IDR714.gif


  - title: Ovals
    icon: mdi:gate
    name: Ovals
    cards:
     - type: entities
    #   title: Ovals
       entities:
         - sensor.ado
         - sensor.trumper
         - sensor.drummoyne
         - sensor.heffron
         - sensor.jubilee
         - sensor.bat_and_ball
         - sensor.david_philips_south
         - sensor.mackey_park
         - sensor.steel_park

  - title: HA Host
    icon: mdi:home-assistant
    name: HA Host
    cards:
      - type: glance
        entities:
          - sensor.last_boot
          - entity: sensor.disk_free_
            name: SD Free
          - entity: sensor.memory_free
            name: Mem Free
          - entity: sensor.homeassistant_v2db
            name: DB
          - entity: sensor.homeassistantlog
            name: log
          
      - type: history-graph
        entities:
           - sensor.processor_use
           - sensor.memory_free
           - sensor.disk_free_
           - sensor.mariadb_size
      - type: custom:tracker-card
        title:
        trackers:
          - sensor.custom_card_tracker
          - sensor.custom_component_tracker

#       - type: entities
#         entities:
#            - sensor.state_changesminute 

#       - type: history-graph
#         entities:
#            - sensor.state_changesminute 

  - title: NAS
    icon: mdi:server
    name: NAS
    cards:
      - type: history-graph
        entities:
           - entity: sensor.onionnas_network_down_eth0
             name: eth0 Down
           - entity: sensor.onionnas_network_up_eth0
             name: eth0 Up
           - entity: sensor.onionnas_cpu_usage
             name: CPU %
           - entity: sensor.onionnas_memory_usage
             name: MEM %
           - entity: sensor.onionnas_system_temperature
             name: CPU
           - entity: sensor.onionnas_temperature_drive_01
             name: Drive 1 
           - entity: sensor.onionnas_temperature_drive_02
             name: Drive 2
           - entity: sensor.onionnas_temperature_drive_03
             name: Drive 3
           - entity: sensor.onionnas_temperature_drive_04
             name: Drive 4


      - type: vertical-stack
        cards:
#           - type: entities
#             entities:
#               - sensor.onionnas_system_temperature

          - type: entities
            name: Statistics
            entities:
              - sensor.onionnas_cpu_temperature
              - sensor.onionnas_cpu_usage
              - sensor.onionnas_memory_available
              - sensor.onionnas_memory_usage
              - sensor.onionnas_memory_used
              - sensor.onionnas_network_link_eth0
              - sensor.onionnas_network_up_eth0
              - sensor.onionnas_network_down_eth0
          - type: glance
            name: Drives
            column_width: 25%
#             title: SMART Status
            entities:
#               - entity: sensor.onionnas_temperature_drive_01
#                 name: D1 Temp
#               - entity: sensor.onionnas_temperature_drive_02
#                 name: D2 Temp
#               - entity: sensor.onionnas_temperature_drive_03
#                 name: D3 Temp
#               - entity: sensor.onionnas_temperature_drive_04
#                 name: D4 Temp
              - entity: sensor.onionnas_smart_status_drive_01
                name: Drive 1
              - entity: sensor.onionnas_smart_status_drive_02
                name: Drive 2
              - entity: sensor.onionnas_smart_status_drive_03
                name: Drive 3
              - entity: sensor.onionnas_smart_status_drive_04
                name: Drive 4

  - title: Network
    icon: mdi:lan
    name: Network
    cards:
#       - type: iframe
#         url: https://grafana.binarylight.com.au/d/xE053cKmk/ubnt-edgerouter-dashboard?refresh=1m&panelId=38&orgId=1&var-dataSource=default&var-host=192.168.0.1&var-intf=eth0&fullscreen
      - type: glance
        name: Speedtest
        title: Speedtest
        entities:
          - sensor.speedtest_download
          - sensor.speedtest_upload
          - sensor.speedtest_ping

      - type: glance
        name: Deluge
        title: Deluge
        entities:
          - sensor.deluge_down_speed
          - sensor.deluge_up_speed
#           - sensor.deluge_status
          - switch.deluge_switch
      - type: history-graph
        hours_to_show: 72
        entities:
           - sensor.deluge_down_speed
           - sensor.deluge_up_speed
           - sensor.speedtest_download
           - sensor.speedtest_upload

# camera.weather_radar
# device_tracker.rudders_iphone_x
# group.all_devices
# group.all_lights
# group.all_remotes
# group.all_switches

# persistent_notification.config_entry_discovery
## remote.living_room
#  remote.shed_tv
 

#  sensor.rudders_iphone_x_battery_level
#  sensor.rudders_iphone_x_battery_state
#  sensor.speedtest_download
#  sensor.speedtest_ping
#  sensor.speedtest_upload
#  switch.deluge_switch
#  switch.festoon_lights
#  zone.home	zoning