sensor:
  - platform: deluge
    host: 192.168.0.50
    username: !secret deluge_userid
    password: !secret deluge_password
    monitored_variables:
      - 'current_status'
      - 'download_speed'
      - 'upload_speed'
  
switch:
  - platform: deluge
    host: 192.168.0.50
    username: !secret deluge_userid
    password: !secret deluge_password
  