sensor:
  - platform: snmp
    name: 'ERX ADSL WAN In'
    host: 192.168.0.1
    baseoid: 1.3.6.1.2.1.31.1.1.1.6.4
    community: 'public'
    version: '2c'
    scan_interval: 10
  
  - platform: snmp
    name: 'ERX ADSL WAN Out'
    host: 192.168.0.1
    baseoid: 1.3.6.1.2.1.31.1.1.1.10.4
    community: 'public'
    version: '2c'
    scan_interval: 10
  
  - platform: statistics
    name: 'ERX ADSL WAN In Stats'
    entity_id: sensor.erx_adsl_wan_in
    sampling_size: 4
    max_age:
      hours: 24
  
  - platform: statistics
    name: 'ERX ADSL WAN Out Stats'
    entity_id: sensor.erx_adsl_wan_out
    sampling_size: 4
    max_age:
      hours: 24
  
  - platform: template
    sensors:
      adsl_internet_in_mbps:
        value_template: "{{ (state_attr('sensor.erx_adsl_wan_in_stats_mean','change_rate')|float*8*(state_attr('sensor.erx_adsl_wan_in_stats_mean', 'sampling_size')-1)/1000000)|round(2) }}"
        unit_of_measurement: 'MBps'
        entity_id: sensor.erx_adsl_wan_in_stats_mean
      adsl_internet_out_mbps:
        value_template: "{{ (state_attr('sensor.erx_adsl_wan_out_stats_mean','change_rate')|float*8*(state_attr('sensor.erx_adsl_wan_out_stats_mean', 'sampling_size')-1)/1000000)|round(2) }}"
        unit_of_measurement: 'MBps'
        entity_id: sensor.erx_adsl_wan_out_stats_mean