sensor:
  - platform: sql
    db_url: !secret mariadb_url
    scan_interval: 60
    queries:
      - name: State Changes/Minute
        query: 'select count(state) as statechanges from states where created > utc_timestamp() - INTERVAL 1 MINUTE;'
        column: 'statechanges'
        unit_of_measurement: 'states'
#         value_template: '{{ value | float }}'