sensor:
  - platform: systemmonitor
    resources:
      - type: disk_free
        arg: /
      - type: memory_free
      - type: processor_use
      - type: last_boot
      - type: network_in 
        arg: eth0
      - type: network_out 
        arg: eth0